import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
// import { act } from '@testing-library/react';
import axios from 'axios';
import { RootState } from '../../app/store';
import { PROPS_AUTHEN, PROPS_PROFILE, PROPS_NICKNAME } from '../types';

const apiUrl = process.env.REACT_APP_DEV_API_URL;

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchAsyncLogin = createAsyncThunk('auth/post', async (authen: PROPS_AUTHEN) => {
  const res = await axios.post(`${apiUrl}authen/jwt/create/`, authen, {
    headers: {
      'Content-Type': 'application/json',
    },
  });
  return res.data;
});

export const fetchAsyncRegister = createAsyncThunk('auth/register', async (authen: PROPS_AUTHEN) => {
  const res = await axios.post(`${apiUrl}api/register/`, authen, {
    headers: {
      'Content-Type': 'application/json',
    },
  });
  return res.data;
});

export const fetchAsyncCreateProfile = createAsyncThunk('profile/post', async (nickName: PROPS_NICKNAME) => {
  const res = await axios.post(`${apiUrl}api/profile/`, nickName, {
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${localStorage.localJWT}`,
    },
  });
  return res.data;
});
export const fetchAsyncUpdateProfile = createAsyncThunk('profile/put', async (profile: PROPS_PROFILE) => {
  const uploadData = new FormData();
  uploadData.append('nickName', profile.nickName);
  profile.img && uploadData.append('img', profile.img, profile.img.name);
  const res = await axios.put(`${apiUrl}api/profile/${profile.id}/`, uploadData, {
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${localStorage.localJWT}`,
    },
  });
  return res.data;
});

export const fetchAsyncGetMyProfile = createAsyncThunk('profile/get', async () => {
  const res = await axios.get(`${apiUrl}api/myprofile/`, {
    headers: {
      Authorization: `Bearer ${localStorage.localJWT}`,
    },
  });
  return res.data[0];
});

export const fetchAsyncGetProfiles = createAsyncThunk('profiles/get', async () => {
  const res = await axios.get(`${apiUrl}api/profile/`, {
    headers: {
      Authorization: `Bearer ${localStorage.localJWT}`,
    },
  });
  return res.data;
});

export const authSlice = createSlice({
  name: 'auth',
  initialState: {
    openSignIn: true,
    openSignUp: false,
    openProfile: false,
    isLoadingAuth: false,
    myProfile: {
      id: 0,
      nickName: '',
      userProfile: 0,
      created_on: '',
      img: '',
    },
    profiles: [
      {
        id: 0,
        nickName: '',
        userProfile: 0,
        created_on: '',
        img: '',
      },
    ],
  },
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    fetchCredStart(state) {
      state.isLoadingAuth = true;
    },
    fetchCredEnd(state) {
      state.isLoadingAuth = false;
    },
    setOpenSignIn(state) {
      state.openSignIn = true;
    },
    resetOpenSignIn(state) {
      state.openSignIn = false;
    },
    setOpenSignUp(state) {
      state.openSignUp = true;
    },
    resetOpenSignUp(state) {
      state.openSignUp = false;
    },
    setOpenProfile(state) {
      state.openProfile = true;
    },
    resetOpenProfile(state) {
      state.openProfile = false;
    },
    editNickname(state, action) {
      state.myProfile.nickName = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder.addCase(fetchAsyncLogin.fulfilled, (state, action) => {
      localStorage.setItem('localJWT', action.payload.access);
    });
    builder.addCase(fetchAsyncCreateProfile.fulfilled, (state, action) => {
      state.myProfile = action.payload;
    });
    builder.addCase(fetchAsyncGetMyProfile.fulfilled, (state, action) => {
      state.myProfile = action.payload;
    });
    builder.addCase(fetchAsyncGetProfiles.fulfilled, (state, action) => {
      state.profiles = action.payload;
    });
    builder.addCase(fetchAsyncUpdateProfile.fulfilled, (state, action) => {
      state.myProfile = action.payload;
      state.profiles = state.profiles.map((prof) => (prof.id === action.payload.id ? action.payload : prof));
    });
  },
});

export const {
  fetchCredStart,
  fetchCredEnd,
  setOpenSignIn,
  resetOpenSignIn,
  setOpenSignUp,
  resetOpenSignUp,
  setOpenProfile,
  resetOpenProfile,
  editNickname,
} = authSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectIsLoadingAuth = (state: RootState) => state.auth.isLoadingAuth;
export const selectOpenSignIn = (state: RootState) => state.auth.openSignIn;
export const selectOpenSignUp = (state: RootState) => state.auth.openSignUp;
export const selectOpenProfile = (state: RootState) => state.auth.openProfile;
export const selectProfile = (state: RootState) => state.auth.myProfile;
export const selectProfiles = (state: RootState) => state.auth.profiles;

export default authSlice.reducer;
